# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
- repo: self

- stage : Provision
  displayName: 'Terrafrom wirh Azure Devops'
  jobs:
  - job: 'Container Build'
    displayName: 'Building Container Instance'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - group: AzureSPvars
    steps:
    - script: |
        set -e
        terraform init -input=false
        terraform plan -input=false
        terraform apply -input=false -auto-approve
      name: 'RunTerraform'
      displayName: 'RunTerraform'
      env: 
        ARM_CLIENT_ID       : $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET   : $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID : $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID       : $(ARM_TENANT_ID)